trigger:
  branches:
    include: [ '*' ] # Trigger on all commits in all branches
  tags:
    include: [ 'v*', '*deploy*' ] # Trigger on v* tags and *deploy* tags

resources:
  repositories:
    - repository: templates
      type: git
      name: ADMS/pipeline-templates

    - repository: db-templates
      type: git
      name: 'Database Management/PipelineTemplates'      

stages:
  - template: Pipelines/website.yml@templates
    parameters:
      artifactFeed: d5f873fd-aea7-4b0f-956a-08364122d906/c8b90219-fc51-43a0-b803-dfc2d668ad9b
      testFileSpec: '**/*UnitTests*.csproj'      
      calculateCoverage: true
      buildQualityCheckWarnings: true
      buildQualityCheckCodeCoverage: true

  - stage: BuildDatabase
    dependsOn: BuildApplication
    displayName: Build Database
    jobs:
      - template: /Jobs/Build/sqlproj.yml@templates
        parameters:
          artifact: 'database-drop-folder'
          buildFileSpec: '**/*ADMSApprentice.sqlproj'
          msbuildAdditionalArguments: '-noWarn:SQL71562,SQL71502,SQL71558'

  - stage: DeployDatabase_Dev
    dependsOn: BuildDatabase
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/dev-deploy')))
    jobs:
    - template: /Jobs/Release/database.yml@db-templates
      parameters:
        dacpacFileSpec: Database.ADMSApprentice.dacpac
        environmentName : ADMSApprentice Database Dev
        databaseName: ADMSApprentice
        artifactName: 'database-drop-folder'
        targetEnvironment: 'Dev'

  - stage: Dev
    dependsOn: DeployDatabase_Dev
    condition:  and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/dev-deploy')))
    variables:
        - group: ServiceAccounts
        - group: DevSettings
        - name: System.Debug
          value: true
        - name: "OurDatabaseSettings.MigrateDatabaseOnStartup"
          value: false
        - name: "OurDatabaseSettings.SeedSampleData"
          value: true
        - name: "OurUSISettings.USIVerifyDisabled"
          value: true
        - name: "OurDatabaseSettings.DatabaseConnectionString"
          value: '$(AdmsApprenticeConnectionString)'
        - name: "OurHttpClientSettings.ReferenceDataEndpointBaseUrl"
          value: '$(ReferenceDataEndpointBaseUrl)'
        - name: port
          value: "80"
        - name: hostname
          value: "admsapi.edc.hosts.devnetwork"
        - name: admsApplicationName
          value: "apprenticeapi"
    jobs:
    - template: Jobs/Release/iiswebapplication.yml@templates
      parameters:
        environmentName: Backend_Dev
        parallelLimit: 100%
        xmlTransformation: false
        xmlVarSubstitution: true
        parentWebsiteName: '$(admsWebsiteName)'
        installDir: $(admsInstallDir)
        takeAppOffline: true
        hostName: ${{ variables.hostName }}
        webAppPoolUsername: "$(ApprenticeAPI_ENETDEV)"
        webAppPoolPassword: "$(ApprenticeAPIPassword_ENETDEV)"
        anonymousAuthentication: true
        windowsAuthentication: false
        webApplicationName: '$(admsApplicationName)'      
        listSites: true

  - stage: DeployDatabase_Test
    dependsOn: BuildDatabase
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/test-deploy')))
    jobs:
    - template: /Jobs/Release/database.yml@db-templates
      parameters:
        dacpacFileSpec: Database.ADMSApprentice.dacpac
        environmentName : ADMSApprentice Database Test
        databaseName: ADMSApprentice
        artifactName: 'database-drop-folder'
        targetEnvironment: 'Test'

  - stage: Test
    dependsOn: DeployDatabase_Test
    condition:  and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/dev-deploy')))
    variables:
        - group: ServiceAccounts
        - group: TestSettings
        - name: System.Debug
          value: true
        - name: "OurDatabaseSettings.MigrateDatabaseOnStartup"
          value: false
        - name: "OurDatabaseSettings.SeedSampleData"
          value: false
        - name: "OurDatabaseSettings.DatabaseConnectionString"
          value: '$(AdmsApprenticeConnectionString)'
        - name: "OurHttpClientSettings.ReferenceDataEndpointBaseUrl"
          value: '$(ReferenceDataEndpointBaseUrl)'
        - name: port
          value: "80"
        - name: hostname
          value: "admsapi.edc.hosts.testnetwork"
        - name: admsApplicationName
          value: "apprenticeapi"
    jobs:
    - template: Jobs/Release/iiswebapplication.yml@templates
      parameters:
        environmentName: Backend_Test
        parallelLimit: 100%
        xmlTransformation: false
        xmlVarSubstitution: true
        parentWebsiteName: '$(admsWebsiteName)'
        installDir: $(admsInstallDir)
        takeAppOffline: true
        hostName: ${{ variables.hostName }}
        webAppPoolUsername: "$(ApprenticeAPI_ENETDEV)"
        webAppPoolPassword: "$(ApprenticeAPIPassword_ENETDEV)"
        anonymousAuthentication: true
        windowsAuthentication: false
        webApplicationName: '$(admsApplicationName)'      
        listSites: true
