trigger:
  branches:
    include: [ '*' ] # Trigger on all commits in all branches
  tags:
    include: [ v* ] # Trigger on v* tags

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOpsManagement/PipelineTemplates

stages:
  - template: Pipelines/website.yml@templates
    parameters:
      artifactFeed: d5f873fd-aea7-4b0f-956a-08364122d906/c8b90219-fc51-43a0-b803-dfc2d668ad9b
      testFileSpec: ''
      calculateCoverage: false